### PR TITLE
Refactoring/expense to transaction

### PR DESCRIPTION
**Pull request by gnomex**
refactoring for #30 

just to know, at `TransactionsController#index`
its being used `transactions = Transaction.where(user_id: current_user.id)`, why not `transactions = current_user.transactions`?

I really appreciate the code quality and standards, congrats

### CODE REVIEW

**Comment by andersonfernandes** [comment]
Hi @gnomex, thanks for the contribution.
I'm going to review as soon as possible.

**Comment by andersonfernandes** [comment]
@gnomex  About your doubt on the `TransactionsController#index`.
Your suggestion is very good, can you cange it on this PR?

**Comment by ayslanmarcelino** [comment]
Changing the model names without raketask won't be a problem environments?

**Comment by gnomex** [comment]
> @gnomex About your doubt on the `TransactionsController#index`.
> Your suggestion is very good, can you cange it on this PR?

sure, going to do asap

**Comment by gnomex** [comment]
> Changing the model names without raketask won't be a problem environments?

I cant find any rake task tied to the old name, so I think it isn't a problem, but, do you know any issue?

since I'm updating all references, it would not be a issue

**Comment by ayslanmarcelino** [comment]
> > Changing the model names without raketask won't be a problem environments?
> 
> I cant find any rake task tied to the old name, so I think it isn't a problem, but, do you know any issue?
> 
> since I'm updating all references, it would not be a issue

ignore my comment, I saw that migrate was made to rename

**Comment by ayslanmarcelino** [comment]
1- change `have_many(:expenses)` to `have_many(:transactions)` in category_spec.rb and user_spec.rb.
2- in `routes.rb` has `resources :expenses`, change to transactions

**Comment by gnomex** [comment]
Thanks @ayslanmarcelino, I did that, but, forgot to commit.

All tests updated and green :heavy_check_mark:

**Review by andersonfernandes — APPROVED** [review]

**Comment by andersonfernandes** [comment]
Nice work @gnomex 🥳 . I'm approving and adding the `hacktoberfest-accepted` label, but I'm goint to wait until @ayslanmarcelino approves to merge it

**Review by ayslanmarcelino — APPROVED** [review]

**Pull request merged**
